
package edu.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 16 16:29:26 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "creatCustomerResponse", namespace = "http://amazon_management.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creatCustomerResponse", namespace = "http://amazon_management.com/")

public class CreatCustomerResponse {

    @XmlElement(name = "return")
    private edu.webservice.model.Customer _return;

    public edu.webservice.model.Customer getReturn() {
        return this._return;
    }

    public void setReturn(edu.webservice.model.Customer new_return)  {
        this._return = new_return;
    }

}

