
package edu.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 16 16:29:26 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "purchaseProductResponse", namespace = "http://amazon_management.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseProductResponse", namespace = "http://amazon_management.com/")

public class PurchaseProductResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<edu.webservice.model.Product> _return;

    public java.util.ArrayList<edu.webservice.model.Product> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<edu.webservice.model.Product> new_return)  {
        this._return = new_return;
    }

}

